
expr
	:             term
    |      op_sum term
    | expr op_sum term
    | asig
    ;

asig
    : symb '=' expr
    ;

term
    :             fact
    | term op_mul fact
    ;

fact
    : prim
    | prim op_exp fact
    ;

prim
    : '3.0'
    | blt2 '(' expr ',' expr ')'
    | const
    | symb
    | blt0 '('               ')'
    |      '(' expr          ')'
    | blt1 '(' expr          ')'
    ;

op_sum
    : '+'
    | '-'
    ;

op_mul
    : '*'
    | '/'
    | '%'
    ;

op_exp
    : '^'
    ;

symb
	: 'v'
	;

const
	: 'E'
	| 'PI'
	;

blt0
	: 'rand'
	;

blt1
	: 'sin'
	| 'cos'
	| 'exp'
	| 'tan'
	| 'log'
	;

blt2
	: 'atan2'
	;
