/* instr.c -- instruction indirection to structures
 * Author: Luis Colorado <luiscoloradourcola@gmail.com>
 *       & Edward Rivas <rivastkw@gmail.com>
 * Date: Sat Mar 22 12:13:29 -05 2025
 * Copyright: (c) 2025-2026 Luis Colorado.  All rights reserved.
 * License: BSD
 */

#include "config.h"
#include "code.h"
#include "instr.h"

#define NELEM(_arr) (sizeof _arr / sizeof _arr[0])

/* LCU: Mon Mar 24 12:23:36 -05 2025
 * ARRAY with definitions for all the instructions.
 * This array contains an entry for each instruction,
 * containing:
 * * the .code_id (the unique number that identifies the
 *   instruction and is also the array index for this entry.
 * * the .name (the name of the instruction, to use it
 *   in the instruction list;)
 * * .exec is the pointer to the function to be executed
 *   when this instruction is to be executed in a program.
 * * .print is the function that is called to print the
 *   trace of the program.
 * This is the code that is generated by the macro INST(_nom),
 * defined next, to later be called with the inclussion of the
 * file "instrucciones.h" with the proper instruction definitions.
 */
const instr instruction_set[] = {
#define INST(_nom,_n, ...)        \
    [INST_##_nom] = {             \
        .code_id  = INST_##_nom,  \
        .n_cells  = _n,           \
        .name     = #_nom,        \
        .exec     = _nom,         \
        .print    = _nom##_prt,   \
        __VA_ARGS__               \
    },
#define SUFF(_typ, _nom, _suf)     \
        ._suf     = _nom##_##_suf,
#include "instrucciones.h"
#undef INST
#undef SUFF
}; /* instruction_set[] */

const size_t instruction_set_len
    = NELEM(instruction_set);

/* instr.c */
