/* type2inst.c -- tablas de punteros a instrucciones para
 *                cada tipo.
 * Author: Edward Rivas <rivastkw@gmail.com>
 * Date: Tue Sep 23 08:51:16 -05 2025
 * Copyright: (c) 2025 Edward Rivas.  All rights reserved.
 * License: BSD
 */

#include "type2inst.h"

type2inst t2i_c = {

    .print   = instruction_set + INST_print,
    .prexpr  = instruction_set + INST_prexpr,
    .inceval = instruction_set + INST_inceval,
    .evalinc = instruction_set + INST_evalinc,
    .deceval = instruction_set + INST_deceval,
    .evaldec = instruction_set + INST_evaldec,
    .addvar  = instruction_set + INST_addvar,
    .subvar  = instruction_set + INST_subvar,
    .mulvar  = instruction_set + INST_mulvar,
    .divvar  = instruction_set + INST_divvar,
    .modvar  = instruction_set + INST_modvar,
    .pwrvar  = instruction_set + INST_pwrvar,
    .arginc  = instruction_set + INST_arginc,
    .incarg  = instruction_set + INST_incarg,
    .decarg  = instruction_set + INST_decarg,
    .argdec  = instruction_set + INST_argdec,
    .addarg  = instruction_set + INST_addarg,
    .subarg  = instruction_set + INST_subarg,
    .mularg  = instruction_set + INST_mularg,
    .divarg  = instruction_set + INST_divarg,
    .modarg  = instruction_set + INST_modarg,
    .pwrarg  = instruction_set + INST_pwrarg,

}, t2i_d = {

    .add     = instruction_set + INST_add,
    .sub     = instruction_set + INST_sub,
    .mul     = instruction_set + INST_mul,
    .divi    = instruction_set + INST_divi,
    .mod     = instruction_set + INST_mod,
    .neg     = instruction_set + INST_neg,
    .pwr     = instruction_set + INST_pwr,
    .print   = instruction_set + INST_print,
    .ge      = instruction_set + INST_ge,
    .le      = instruction_set + INST_le,
    .gt      = instruction_set + INST_gt,
    .lt      = instruction_set + INST_lt,
    .eq      = instruction_set + INST_eq,
    .ne      = instruction_set + INST_ne,
    .not     = instruction_set + INST_not,
    .prexpr  = instruction_set + INST_prexpr,
    .inceval = instruction_set + INST_inceval,
    .evalinc = instruction_set + INST_evalinc,
    .deceval = instruction_set + INST_deceval,
    .evaldec = instruction_set + INST_evaldec,
    .addvar  = instruction_set + INST_addvar,
    .subvar  = instruction_set + INST_subvar,
    .mulvar  = instruction_set + INST_mulvar,
    .divvar  = instruction_set + INST_divvar,
    .modvar  = instruction_set + INST_modvar,
    .pwrvar  = instruction_set + INST_pwrvar,
    .arginc  = instruction_set + INST_arginc,
    .incarg  = instruction_set + INST_incarg,
    .decarg  = instruction_set + INST_decarg,
    .argdec  = instruction_set + INST_argdec,
    .addarg  = instruction_set + INST_addarg,
    .subarg  = instruction_set + INST_subarg,
    .mularg  = instruction_set + INST_mularg,
    .divarg  = instruction_set + INST_divarg,
    .modarg  = instruction_set + INST_modarg,
    .pwrarg  = instruction_set + INST_pwrarg,

}, t2i_f = {

    .print   = instruction_set + INST_print,
    .prexpr  = instruction_set + INST_prexpr,
    .inceval = instruction_set + INST_inceval,
    .evalinc = instruction_set + INST_evalinc,
    .deceval = instruction_set + INST_deceval,
    .evaldec = instruction_set + INST_evaldec,
    .addvar  = instruction_set + INST_addvar,
    .subvar  = instruction_set + INST_subvar,
    .mulvar  = instruction_set + INST_mulvar,
    .divvar  = instruction_set + INST_divvar,
    .modvar  = instruction_set + INST_modvar,
    .pwrvar  = instruction_set + INST_pwrvar,
    .arginc  = instruction_set + INST_arginc,
    .incarg  = instruction_set + INST_incarg,
    .decarg  = instruction_set + INST_decarg,
    .argdec  = instruction_set + INST_argdec,
    .addarg  = instruction_set + INST_addarg,
    .subarg  = instruction_set + INST_subarg,
    .mularg  = instruction_set + INST_mularg,
    .divarg  = instruction_set + INST_divarg,
    .modarg  = instruction_set + INST_modarg,
    .pwrarg  = instruction_set + INST_pwrarg,

}, t2i_i = {

    .add     = instruction_set + INST_add,
    .sub     = instruction_set + INST_sub,
    .mul     = instruction_set + INST_mul,
    .divi    = instruction_set + INST_divi,
    .mod     = instruction_set + INST_mod,
    .neg     = instruction_set + INST_neg,
    .pwr     = instruction_set + INST_pwr,
    .print   = instruction_set + INST_print,
    .ge      = instruction_set + INST_ge,
    .le      = instruction_set + INST_le,
    .gt      = instruction_set + INST_gt,
    .lt      = instruction_set + INST_lt,
    .eq      = instruction_set + INST_eq,
    .ne      = instruction_set + INST_ne,
    .not     = instruction_set + INST_not,
    .prexpr  = instruction_set + INST_prexpr,
    .inceval = instruction_set + INST_inceval,
    .evalinc = instruction_set + INST_evalinc,
    .deceval = instruction_set + INST_deceval,
    .evaldec = instruction_set + INST_evaldec,
    .addvar  = instruction_set + INST_addvar,
    .subvar  = instruction_set + INST_subvar,
    .mulvar  = instruction_set + INST_mulvar,
    .divvar  = instruction_set + INST_divvar,
    .modvar  = instruction_set + INST_modvar,
    .pwrvar  = instruction_set + INST_pwrvar,
    .arginc  = instruction_set + INST_arginc,
    .incarg  = instruction_set + INST_incarg,
    .decarg  = instruction_set + INST_decarg,
    .argdec  = instruction_set + INST_argdec,
    .addarg  = instruction_set + INST_addarg,
    .subarg  = instruction_set + INST_subarg,
    .mularg  = instruction_set + INST_mularg,
    .divarg  = instruction_set + INST_divarg,
    .modarg  = instruction_set + INST_modarg,
    .pwrarg  = instruction_set + INST_pwrarg,

}, t2i_l = {

    .add     = instruction_set + INST_add,
    .sub     = instruction_set + INST_sub,
    .mul     = instruction_set + INST_mul,
    .divi    = instruction_set + INST_divi,
    .mod     = instruction_set + INST_mod,
    .neg     = instruction_set + INST_neg,
    .pwr     = instruction_set + INST_pwr,
    .print   = instruction_set + INST_print,
    .ge      = instruction_set + INST_ge,
    .le      = instruction_set + INST_le,
    .gt      = instruction_set + INST_gt,
    .lt      = instruction_set + INST_lt,
    .eq      = instruction_set + INST_eq,
    .ne      = instruction_set + INST_ne,
    .not     = instruction_set + INST_not,
    .prexpr  = instruction_set + INST_prexpr,
    .inceval = instruction_set + INST_inceval,
    .evalinc = instruction_set + INST_evalinc,
    .deceval = instruction_set + INST_deceval,
    .evaldec = instruction_set + INST_evaldec,
    .addvar  = instruction_set + INST_addvar,
    .subvar  = instruction_set + INST_subvar,
    .mulvar  = instruction_set + INST_mulvar,
    .divvar  = instruction_set + INST_divvar,
    .modvar  = instruction_set + INST_modvar,
    .pwrvar  = instruction_set + INST_pwrvar,
    .arginc  = instruction_set + INST_arginc,
    .incarg  = instruction_set + INST_incarg,
    .decarg  = instruction_set + INST_decarg,
    .argdec  = instruction_set + INST_argdec,
    .addarg  = instruction_set + INST_addarg,
    .subarg  = instruction_set + INST_subarg,
    .mularg  = instruction_set + INST_mularg,
    .divarg  = instruction_set + INST_divarg,
    .modarg  = instruction_set + INST_modarg,
    .pwrarg  = instruction_set + INST_pwrarg,

},  t2i_s = {

    .print   = instruction_set + INST_print,
    .prexpr  = instruction_set + INST_prexpr,
    .addvar  = instruction_set + INST_addvar,
    .subvar  = instruction_set + INST_subvar,
    .mulvar  = instruction_set + INST_mulvar,
    .divvar  = instruction_set + INST_divvar,
    .modvar  = instruction_set + INST_modvar,
    .pwrvar  = instruction_set + INST_pwrvar,
    .arginc  = instruction_set + INST_arginc,
    .incarg  = instruction_set + INST_incarg,
    .decarg  = instruction_set + INST_decarg,
    .argdec  = instruction_set + INST_argdec,
    .addarg  = instruction_set + INST_addarg,
    .subarg  = instruction_set + INST_subarg,
    .mularg  = instruction_set + INST_mularg,
    .divarg  = instruction_set + INST_divarg,
    .modarg  = instruction_set + INST_modarg,
    .pwrarg  = instruction_set + INST_pwrarg,

}; /* t2i_s */
