/* type2inst.c-prueba -- tablas de punteros a instrucciones para
 *                cada tipo.
 * Author: Edward Rivas <rivastkw@gmail.com>
 * Date: Tue Sep 30 09:54:48 -05 2025
 * Copyright: (c) 2025 Edward Rivas.  All rights reserved.
 * License: BSD
 * NOTE: This file generated automatically, don't edit.
 */

#include "type2inst.h"

type2inst t2i_c = {

    .constpush        = instruction_set + INST_constpush_c,
    .eval        = instruction_set + INST_eval_c,
    .assign        = instruction_set + INST_assign_c,
    .print        = instruction_set + INST_print_c,
    .prexpr        = instruction_set + INST_prexpr_c,
    .inceval        = instruction_set + INST_inceval_c,
    .evalinc        = instruction_set + INST_evalinc_c,
    .deceval        = instruction_set + INST_deceval_c,
    .evaldec        = instruction_set + INST_evaldec_c,
    .addvar        = instruction_set + INST_addvar_c,
    .subvar        = instruction_set + INST_subvar_c,
    .mulvar        = instruction_set + INST_mulvar_c,
    .divvar        = instruction_set + INST_divvar_c,
    .modvar        = instruction_set + INST_modvar_c,
    .pwrvar        = instruction_set + INST_pwrvar_c,
    .arginc        = instruction_set + INST_arginc_c,
    .incarg        = instruction_set + INST_incarg_c,
    .decarg        = instruction_set + INST_decarg_c,
    .argdec        = instruction_set + INST_argdec_c,
    .addarg        = instruction_set + INST_addarg_c,
    .subarg        = instruction_set + INST_subarg_c,
    .mularg        = instruction_set + INST_mularg_c,
    .divarg        = instruction_set + INST_divarg_c,
    .modarg        = instruction_set + INST_modarg_c,
    .pwrarg        = instruction_set + INST_pwrarg_c,

}, t2i_d = {

    .constpush        = instruction_set + INST_constpush_d,
    .add        = instruction_set + INST_add_d,
    .sub        = instruction_set + INST_sub_d,
    .mul        = instruction_set + INST_mul_d,
    .divi        = instruction_set + INST_divi_d,
    .mod        = instruction_set + INST_mod_d,
    .neg        = instruction_set + INST_neg_d,
    .pwr        = instruction_set + INST_pwr_d,
    .eval        = instruction_set + INST_eval_d,
    .assign        = instruction_set + INST_assign_d,
    .print        = instruction_set + INST_print_d,
    .ge        = instruction_set + INST_ge_d,
    .le        = instruction_set + INST_le_d,
    .gt        = instruction_set + INST_gt_d,
    .lt        = instruction_set + INST_lt_d,
    .eq        = instruction_set + INST_eq_d,
    .ne        = instruction_set + INST_ne_d,
    .not        = instruction_set + INST_not_d,
    .prexpr        = instruction_set + INST_prexpr_d,
    .inceval        = instruction_set + INST_inceval_d,
    .evalinc        = instruction_set + INST_evalinc_d,
    .deceval        = instruction_set + INST_deceval_d,
    .evaldec        = instruction_set + INST_evaldec_d,
    .addvar        = instruction_set + INST_addvar_d,
    .subvar        = instruction_set + INST_subvar_d,
    .mulvar        = instruction_set + INST_mulvar_d,
    .divvar        = instruction_set + INST_divvar_d,
    .modvar        = instruction_set + INST_modvar_d,
    .pwrvar        = instruction_set + INST_pwrvar_d,
    .arginc        = instruction_set + INST_arginc_d,
    .incarg        = instruction_set + INST_incarg_d,
    .decarg        = instruction_set + INST_decarg_d,
    .argdec        = instruction_set + INST_argdec_d,
    .addarg        = instruction_set + INST_addarg_d,
    .subarg        = instruction_set + INST_subarg_d,
    .mularg        = instruction_set + INST_mularg_d,
    .divarg        = instruction_set + INST_divarg_d,
    .modarg        = instruction_set + INST_modarg_d,
    .pwrarg        = instruction_set + INST_pwrarg_d,

}, t2i_f = {

    .constpush        = instruction_set + INST_constpush_d,
    .add        = instruction_set + INST_add_d,
    .sub        = instruction_set + INST_sub_d,
    .mul        = instruction_set + INST_mul_d,
    .divi        = instruction_set + INST_divi_d,
    .mod        = instruction_set + INST_mod_d,
    .neg        = instruction_set + INST_neg_d,
    .pwr        = instruction_set + INST_pwr_d,
    .eval        = instruction_set + INST_eval_d,
    .assign        = instruction_set + INST_assign_d,
    .print        = instruction_set + INST_print_d,
    .ge        = instruction_set + INST_ge_d,
    .le        = instruction_set + INST_le_d,
    .gt        = instruction_set + INST_gt_d,
    .lt        = instruction_set + INST_lt_d,
    .eq        = instruction_set + INST_eq_d,
    .ne        = instruction_set + INST_ne_d,
    .not        = instruction_set + INST_not_d,
    .prexpr        = instruction_set + INST_prexpr_d,
    .inceval        = instruction_set + INST_inceval_d,
    .evalinc        = instruction_set + INST_evalinc_d,
    .deceval        = instruction_set + INST_deceval_d,
    .evaldec        = instruction_set + INST_evaldec_d,
    .addvar        = instruction_set + INST_addvar_d,
    .subvar        = instruction_set + INST_subvar_d,
    .mulvar        = instruction_set + INST_mulvar_d,
    .divvar        = instruction_set + INST_divvar_d,
    .modvar        = instruction_set + INST_modvar_d,
    .pwrvar        = instruction_set + INST_pwrvar_d,
    .arginc        = instruction_set + INST_arginc_d,
    .incarg        = instruction_set + INST_incarg_d,
    .decarg        = instruction_set + INST_decarg_d,
    .argdec        = instruction_set + INST_argdec_d,
    .addarg        = instruction_set + INST_addarg_d,
    .subarg        = instruction_set + INST_subarg_d,
    .mularg        = instruction_set + INST_mularg_d,
    .divarg        = instruction_set + INST_divarg_d,
    .modarg        = instruction_set + INST_modarg_d,
    .pwrarg        = instruction_set + INST_pwrarg_d,

}, t2i_i = {

    .constpush        = instruction_set + INST_constpush_i,
    .add        = instruction_set + INST_add_i,
    .sub        = instruction_set + INST_sub_i,
    .mul        = instruction_set + INST_mul_i,
    .divi        = instruction_set + INST_divi_i,
    .mod        = instruction_set + INST_mod_i,
    .neg        = instruction_set + INST_neg_i,
    .pwr        = instruction_set + INST_pwr_i,
    .eval        = instruction_set + INST_eval_i,
    .assign        = instruction_set + INST_assign_i,
    .print        = instruction_set + INST_print_i,
    .ge        = instruction_set + INST_ge_i,
    .le        = instruction_set + INST_le_i,
    .gt        = instruction_set + INST_gt_i,
    .lt        = instruction_set + INST_lt_i,
    .eq        = instruction_set + INST_eq_i,
    .ne        = instruction_set + INST_ne_i,
    .not        = instruction_set + INST_not_i,
    .prexpr        = instruction_set + INST_prexpr_i,
    .inceval        = instruction_set + INST_inceval_i,
    .evalinc        = instruction_set + INST_evalinc_i,
    .deceval        = instruction_set + INST_deceval_i,
    .evaldec        = instruction_set + INST_evaldec_i,
    .addvar        = instruction_set + INST_addvar_i,
    .subvar        = instruction_set + INST_subvar_i,
    .mulvar        = instruction_set + INST_mulvar_i,
    .divvar        = instruction_set + INST_divvar_i,
    .modvar        = instruction_set + INST_modvar_i,
    .pwrvar        = instruction_set + INST_pwrvar_i,
    .arginc        = instruction_set + INST_arginc_i,
    .incarg        = instruction_set + INST_incarg_i,
    .decarg        = instruction_set + INST_decarg_i,
    .argdec        = instruction_set + INST_argdec_i,
    .addarg        = instruction_set + INST_addarg_i,
    .subarg        = instruction_set + INST_subarg_i,
    .mularg        = instruction_set + INST_mularg_i,
    .divarg        = instruction_set + INST_divarg_i,
    .modarg        = instruction_set + INST_modarg_i,
    .pwrarg        = instruction_set + INST_pwrarg_i,

}, t2i_l = {

    .constpush        = instruction_set + INST_constpush_l,
    .add        = instruction_set + INST_add_l,
    .sub        = instruction_set + INST_sub_l,
    .mul        = instruction_set + INST_mul_l,
    .divi        = instruction_set + INST_divi_l,
    .mod        = instruction_set + INST_mod_l,
    .neg        = instruction_set + INST_neg_l,
    .pwr        = instruction_set + INST_pwr_l,
    .eval        = instruction_set + INST_eval_l,
    .assign        = instruction_set + INST_assign_l,
    .print        = instruction_set + INST_print_l,
    .ge        = instruction_set + INST_ge_l,
    .le        = instruction_set + INST_le_l,
    .gt        = instruction_set + INST_gt_l,
    .lt        = instruction_set + INST_lt_l,
    .eq        = instruction_set + INST_eq_l,
    .ne        = instruction_set + INST_ne_l,
    .not        = instruction_set + INST_not_l,
    .prexpr        = instruction_set + INST_prexpr_l,
    .inceval        = instruction_set + INST_inceval_l,
    .evalinc        = instruction_set + INST_evalinc_l,
    .deceval        = instruction_set + INST_deceval_l,
    .evaldec        = instruction_set + INST_evaldec_l,
    .addvar        = instruction_set + INST_addvar_l,
    .subvar        = instruction_set + INST_subvar_l,
    .mulvar        = instruction_set + INST_mulvar_l,
    .divvar        = instruction_set + INST_divvar_l,
    .modvar        = instruction_set + INST_modvar_l,
    .pwrvar        = instruction_set + INST_pwrvar_l,
    .arginc        = instruction_set + INST_arginc_l,
    .incarg        = instruction_set + INST_incarg_l,
    .decarg        = instruction_set + INST_decarg_l,
    .argdec        = instruction_set + INST_argdec_l,
    .addarg        = instruction_set + INST_addarg_l,
    .subarg        = instruction_set + INST_subarg_l,
    .mularg        = instruction_set + INST_mularg_l,
    .divarg        = instruction_set + INST_divarg_l,
    .modarg        = instruction_set + INST_modarg_l,
    .pwrarg        = instruction_set + INST_pwrarg_l,

},  t2i_s = {

    .constpush        = instruction_set + INST_constpush_s,
    .eval        = instruction_set + INST_eval_s,
    .assign        = instruction_set + INST_assign_s,
    .print        = instruction_set + INST_print_s,
    .prexpr        = instruction_set + INST_prexpr_s,
    .addvar        = instruction_set + INST_addvar_s,
    .subvar        = instruction_set + INST_subvar_s,
    .mulvar        = instruction_set + INST_mulvar_s,
    .divvar        = instruction_set + INST_divvar_s,
    .modvar        = instruction_set + INST_modvar_s,
    .pwrvar        = instruction_set + INST_pwrvar_s,
    .arginc        = instruction_set + INST_arginc_s,
    .incarg        = instruction_set + INST_incarg_s,
    .decarg        = instruction_set + INST_decarg_s,
    .argdec        = instruction_set + INST_argdec_s,
    .addarg        = instruction_set + INST_addarg_s,
    .subarg        = instruction_set + INST_subarg_s,
    .mularg        = instruction_set + INST_mularg_s,
    .divarg        = instruction_set + INST_divarg_s,
    .modarg        = instruction_set + INST_modarg_s,
    .pwrarg        = instruction_set + INST_pwrarg_s,

}; /* t2i_s */
